configfile: "config/config.yaml"

container: "docker://condaforge/miniforge3:25.11.0-0"

include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/vep.smk"
include: "rules/candidate_mutations.smk"
include: "rules/qc.smk"


rule all:
    input:
        get_final_output,
