# Path to sample sheet (CSV format)
samples: "config/samples.csv"
# Path to MultiQC config
multiqc_config: "config/multiqc_config.yaml"
# Path to reference fasta file
ref_fasta: "data/ref.fa"
# Path to BED file with masked regions
regions_to_mask: "data/repeatmasked.bed"
# Path to GFF annotation file
gff_annotation: "data/annotation.gff3"

vep:
  # Shift indels to the most 3prime 
  shift_3prime: True
  # Add hgvs annotation
  hgvs: True
  # Additional options for VEP
  extra: ""

# Remove duplicate reads with picard
remove_duplicates : False

params:
  #fastp: "-g -l 35 -q 20"
  fastp: ""
  freebayes:
    #extra: "--use-best-n-alleles 4 --min-mapping-quality 30 -q 20"
    extra: ""
    chunksize: 100000

candidate_mutations:
  # Minimum depth in the samples to consider a variant
  min_dp: 10
  # Minimum difference in allele frequency between WT and Mutant to report a variant
  report_delta: 0.9
  # Minimum difference in allele frequency between WT and Mutant to plot a variant
  plot_delta: 0.5
  # Set true to not reporting variants in masked regions
  skip_masked: False
  # Set true to keep all annotations from VEP in the final table
  keep_all_annotations: True
  # You can set different delta thresholds for different sequences (e.g. organellar genomes)
  #delta_seq_name:
  #  chr_1 : 0.5
  #  mitogenome : 0.05
  #  plastome : 0.05
